import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUser() {
     throw new Error("Testing error boundary!") // for testing error
}


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await getUser();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <Link href={'/'}>Home &nbsp;</Link>
          <Link href={'/blog'}>Blog &nbsp;</Link>
          <Link href={'/about'}>About &nbsp;</Link>
          <Link href={'/secret'}>Secret &nbsp;</Link>
        </nav>
        <hr />
        {children}</body>
    </html>
  );
}
