import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUser() {
  throw new Error("Testing error boundary!"); // for testing error
}

export default async function RootLayout({
  children, params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: String}>
}>) {
  // const user = await getUser();
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound;
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav>
          <Link href={`/${locale}`}>Home &nbsp;</Link>
          <Link href={`/${locale}/blog`}>Blog &nbsp;</Link>
          <Link href={`/${locale}/about`}>About &nbsp;</Link>
          <Link href={`/${locale}/secret`}>Secret &nbsp;</Link>
          <Link href={`/${locale}/note`}>Note &nbsp;</Link>
        </nav>
        <hr />
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
